#!/usr/bin/env python

# -*-Python-*-
# checkhistory - check shell history files for passwords

import os, re

patstr = ['^(?:|.*[ |&])mysql(?:dump)? .*-p\S',
          '^(?:|.*[ |&])sshpass .*-p', '^curl .*(?:-u|-user) .*:',
          '^(?:|.*[ |&])lynx .*-p?auth=.*:',
          '^(?:|.*[ |&])wget .*--(?:ftp-|http-)?password',
          'sudo .*-S',
          '^(?:|.*[ |&])sqlplus +(?:.* +)?.+/.+',
          '^(?:|.*[ |&])user(?:add|mod) .*(?:-p|--password) ']
patterns = [re.compile(a) for a in patstr]
zshclean = re.compile('^: \d+:0;')

def checkfile(histfile):
    '''take a shell history and check which exposed passwords match'''
    print 'Passwords in %s' % histfile
    with open(histfile) as f:
        for linenum, line in enumerate(f):
            if 'zsh' in histfile:
                line = zshclean.sub('', line)
            for pattern in patterns:
                if pattern.search(line):
                    warnit(linenum, line.rstrip())

def warnit(linenum, line):
    print "%s: %s" % (linenum, line)

def main():
    histfiles = ('.bash_history', '.zsh_history')
    for histfile in histfiles:
        fullpath = os.path.expanduser(('~/%s' % histfile))
        if os.path.exists(fullpath):
            checkfile(fullpath)

if __name__ == '__main__':
    main()
