#!/bin/bash

# exmv - EXtract & MoVe

ARCFILE=$(realpath "$1")
DESTPATH="${2:-$EXMVPATH}"

USAGE="exmv [archivefile] [destpath]"

testargs () {
    if [[ ! -f "$ARCFILE" ]]; then
	echo "Bad file"
	exit 1
    fi
}

testdir () {
    if [[ ! -d "$DESTPATH" ]]; then
	echo "Bad dir"
	exit 2
    fi
}


testargs
testdir

# TODO: if files already in dir, don't create new one

# strip dir & extension from $ARCFILE
BAREPATH=$(basename "$ARCFILE")
NEWDIR="${BAREPATH%.*}"
NEWFULLDIR="$DESTPATH/$NEWDIR"

mkdir "$NEWFULLDIR" || exit 6
cd "$NEWFULLDIR" || exit 3

unrar x "$ORIGDIR/$ARCFILE" || exit 5

# check if subdirectories, if so flatten files
find . -maxdepth 1 -mindepth 1 -type d -print0 | while read -d $'\0' subdir
do
    # don't care about filename clash for now
    mv "$subdir"/* .
    rmdir "$subdir"
done

rm "$ARCFILE"

exit
