#!/usr/bin/expect -f
# -*-Tcl-*-
# if-autocert - autoaccept IMAP TLS certificates for imapfilter
# (google rotates very rapidly). ONLY USE THIS IF YOU ARE COMFORTABLE
# WITH THE SECURITY IMPLICATIONS
#
spawn imapfilter -c $env(HOME)/.imapfilter/google.lua
expect {
    "ermanently*" { send "p\r\n";
	exp_continue
	# interact return
    }
    eof { exit }
}


