#!/usr/bin/env python

# md5files - rename files according to their md5sum
# USAGE: md5files "*.mp3"

import sys
import glob
import md5
import os

files = glob.glob(sys.argv[1])

for myfile in files:
    ext = '.' + myfile.split('.')[-1]
    newname = md5.md5(myfile).hexdigest() + ext
    print "Renaming %s to %s" % (myfile, newname)
    os.rename(myfile, newname)


