#!/usr/bin/env python3
# -*-Python-*-
# umax-restart - restart a UMaxHosting server automatically via
# python-selenium
# [c] jamespo [at] gmail [dot] com 2019

import configparser
import os.path
from shutil import which
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options


def getcreds(debug=False):
    '''get conf from ~/.config/.umaxcreds'''
    config = configparser.RawConfigParser()  # don't interpolate
    config_path = os.path.join(os.path.expanduser("~"), '.config',
                               '.umaxcreds')
    config.read(config_path)
    return config


def get_browser_location():
    '''get chromium location'''
    for loc in (which('chromium'), which('chromium-browser')):
        if loc is not None:
            return loc


def main(config, debug=False):
    '''log in navigate and reboot'''
    user, pw = config.get('credentials', 'username'), \
        config.get('credentials', 'password')
    domain = config.get('server', 'domain')

    chrome_options = Options()
    if not debug:
        chrome_options.add_argument("--headless")
        # chrome_options.add_argument('--no-sandbox')
        # chrome_options.add_argument("--start-maximized")
    chrome_options.binary_location = get_browser_location()
    driver = webdriver.Chrome(executable_path=which('chromedriver'),
                              options=chrome_options)

    if not debug:
        driver.set_window_size(1024, 768)

    driver.get('https://www.umaxhosting.com/manage/clientarea.php')

    username_field = driver.find_element_by_id("inputEmail")
    username_field.clear()
    username_field.send_keys(user)

    pw_field = driver.find_element_by_id("inputPassword")
    pw_field.clear()
    pw_field.send_keys(pw)
    pw_field.send_keys(Keys.RETURN)
    sleep(2)  # TODO: convert sleeps to webdriverwait

    assert domain in driver.page_source

    server = driver.find_element_by_partial_link_text(domain)
    server.click()
    sleep(2)

    # TODO: optionally check if server status is Active
    assert 'Reboot' in driver.page_source

    if debug != '2':
        # DEBUG: don't click reboot if DEBUG==2
        server = driver.find_element_by_partial_link_text('Reboot')
        server.click()
        sleep(2)
        try:
            assert 'Action Completed Successfully' in driver.page_source
            print('%s rebooted' % domain)
        except:
            print('%s reboot FAILED' % domain)
    else:
        print('DEBUG mode - no reboot')

    if DEBUG:
        sleep(10)
    driver.quit()


if __name__ == "__main__":
    DEBUG = os.getenv('DEBUG')
    if DEBUG:
        print('DEBUG mode %s' % DEBUG)
    config = getcreds(DEBUG)
    main(config, DEBUG)
